---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package
    package:
      name:
        - apache2
        - libapache2-mod-php
        - nmap
        - mysql-server
      state: latest
    when: ansible_distribution == "Ubuntu"

