---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package
    apt:
      name: apache2

  - name: add php
    apt:
      name: libapache2-mod-php

  - name: nmap
    apt:
      name: nmap

  - name: sql install
    apt:
      name: mysql-server

  - name: Allow all access to tcp port80
    community.general.ufw:
      rule: allow
      port: '80'
      proto: tcp

  - name: Allow all access to tcp port443
    community.general.ufw:
      rule: allow
      port: '443'
      proto: tcp
