---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package
    apt:
      name: apache2
      state: absent

  - name: add php
    apt:
      name: libapache2-mod-php
      state: absent

  - name: nmap
    apt:
      name: nmap
      state: absent

  - name: sql install
    apt:
      name: mysql-server
      state: absent
