---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates(centos)
    apt:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: web_servers
  become: true
  tasks:

    - name: install apache and php for servers
      tags: web server,apache2,ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install website for internet
      unarchive:
        src: https://www.free-css.com/assets/files/free-css-templates/download/page280/sungla.zip
        dest: /var/www/html
        remote_src: yes
        mode: 0755
        owner: root
        group: root

    - name: copy default html file for site
      tags: apache,apache2,httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0755

    - name: start httpd(ubuntu)
      tags: apache,apache2,httpd
      service:
        name: apache2
        state: start

- hosts: db_servers
  become: true
  tasks:

    - name: installing sql server
      tags: sql,mysql,db
      apt:
        name:
          - mysql-server
        state: latest
      when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

    - name: installing file server
      tags: file,storage
      apt:
        name: samba
        state: latest
      
